#!/bin/bash

service::config_set() {
  config::check_or_set $1 $2 $SERVICE_CONFIG "${@:3}"
}

check() {
  if [ "$DEBUG" = "true" ]; then
    log::info "[DEBUG][service]: $SERVICE_CONFIG"
    cat $SERVICE_CONFIG
  fi

  # service::config_set SERVICE_PUPPETEER_PORT text "Port" 8024

  service::config_set SERVICE_PUPPETEER_BROWSER_WS_ENDPOINT text "Browser WS Endpoint" "ws://browserless:3000"
}

check $@
